global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'linux-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['centos1:9100']
  - job_name: 'onesql'
    metrics_path: /metrics
    static_configs:
      - targets: ['172.17.0.1:9191']
  - job_name: 'pushgateway'
    honor_labels: true
    metrics_path: /metrics
    static_configs:
      - targets: ['pushgateway:9091']




                
